### ISSUE TITLE
calcClosenessCriterion

### ISSUE THREAD

**Issue by ZhangXinchu** [HMX2013/L-shape-fitting-3D-LiDAR-ROS#1]
您分享的代码中calcClosenessCriterion函数，和原文Alg4的4和5公式处不太一致，还有您在这个函数中有四个相似度较大的代码块最终返回了最大的beta，想请教您这部分？还有想咨询您的工程验证过效果了吗？

**Comment by morte2025** [comment]
代码里写的有点乱，都返回beta, 那是对应不同的Criterion计算方法，那篇论文有Area Minimization ，Closeness Maximization 和 Variance Minimization三条准则， 我一直在测试，对于车这种或者点云投影接近L形的效果都不错，比那个pca包围盒好多了，但是这种算法速度有点慢，搜索的方法迭代次数多有点慢，我一直在改进，可以关注以后的更新
